@devHost = http://localhost:3000
@prodHost = https://critter-creator-cse341.onrender.com

### *********************GET ALL*********************
GET {{devHost}}/critters
### ********************GET BY ID********************
GET {{devHost}}/critters/6652b844a2aaf13dff8f4c88
### **********************POST***********************
POST {{devHost}}/critters HTTP/1.1
content-type: application/json

{
  "name": "Jill",
  "intelligence": "4",
  "body_plan": "crab-like",
  "color_code": "0000ff"
}
### ***********************PUT***********************
PUT {{devHost}}/critters/6652bbc76792f4e5e8633933 HTTP/1.1
content-type: application/json
  
{
  "name": "Jill",
  "intelligence": "5",
  "body_plan": "crab-like",
  "color_code": "0000ff"
}
### *********************DELETE**********************
DELETE {{devHost}}/critters/665d20f733da326e39492eee

###
### -------------------------------------------------
###                     PROD HOST
### -------------------------------------------------
###

### *********************GET ALL*********************
GET {{prodHost}}/critters

### ********************GET BY ID********************
GET {{prodHost}}/critters/6652b844a2aaf13dff8f4c88

### **********************POST***********************
POST {{prodHost}}/critters HTTP/1.1
content-type: application/json

{
  "name": "Jill",
  "intelligence": "4",
  "body_plan": "crab-like",
  "color_code": "0000ff"
}

### ***********************PUT***********************
PUT {{prodHost}}/critters/6652bbc76792f4e5e8633933 HTTP/1.1
content-type: application/json
  
{
  "name": "Jill",
  "intelligence": "5",
  "body_plan": "crab-like",
  "color_code": "0000ff"
}

### *********************DELETE**********************
DELETE {{prodHost}}/critters/665d20f733da326e39492eee